package mse.topology;

import mse.topology.TopologyLoader.NeighborJson;
import mse.topology.TopologyLoader.NodeJson;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;

/**
 * CLI tool: converts topology.json into a topology.h C header for the Arduino Mega firmware.
 *
 * Usage: TopologyCompiler <topology.json> <output.h>
 */
public class TopologyCompiler {

    public static void main(String[] args) throws IOException {
        if (args.length < 2) {
            System.err.println("Usage: TopologyCompiler <topology.json> <output.h>");
            System.exit(1);
        }
        TopologyLoader.LoadResult result = TopologyLoader.load(Path.of(args[0]));
        String header = compile(result.nodeJsons);
        Files.writeString(Path.of(args[1]), header);
        System.out.println("Wrote " + args[1] + "  (" + result.nodeJsons.size() + " nodes)");
    }

    /** Converts a node list into the content of topology.h. Package-private for testing. */
    static String compile(List<NodeJson> nodes) {
        int n = nodes.size();

        Map<String, Integer> idx = new LinkedHashMap<>();
        for (int i = 0; i < n; i++) idx.put(nodes.get(i).nodeId, i);

        int maxN = 0;
        for (NodeJson node : nodes) {
            if (node.neighbors != null) maxN = Math.max(maxN, node.neighbors.size());
        }

        StringBuilder sb = new StringBuilder();
        sb.append("// Auto-generated by TopologyCompiler — do not edit by hand\n");
        sb.append("#pragma once\n");
        sb.append("#include <stdint.h>\n");
        sb.append("#include <stdbool.h>\n\n");
        sb.append("#define NUM_NODES ").append(n).append("\n");
        sb.append("#define MAX_NEIGHBORS ").append(maxN).append("\n\n");

        sb.append("static const char* const NODE_IDS[NUM_NODES] = {");
        for (int i = 0; i < n; i++) {
            sb.append('"').append(nodes.get(i).nodeId).append('"');
            if (i < n - 1) sb.append(", ");
        }
        sb.append("};\n");

        sb.append("static const bool IS_EXIT[NUM_NODES] = {");
        for (int i = 0; i < n; i++) {
            sb.append(nodes.get(i).isExit ? "true" : "false");
            if (i < n - 1) sb.append(", ");
        }
        sb.append("};\n\n");

        sb.append("static const int8_t NEIGHBOR_IDX[NUM_NODES][MAX_NEIGHBORS] = {\n");
        for (int i = 0; i < n; i++) {
            List<NeighborJson> nbs = neighbors(nodes.get(i));
            sb.append("    {");
            for (int j = 0; j < maxN; j++) {
                sb.append(j < nbs.size() ? idx.get(nbs.get(j).nodeId) : -1);
                if (j < maxN - 1) sb.append(", ");
            }
            sb.append("}");
            if (i < n - 1) sb.append(",");
            sb.append("   // ").append(nodes.get(i).nodeId).append("\n");
        }
        sb.append("};\n\n");

        sb.append("static const float WEIGHTS[NUM_NODES][MAX_NEIGHBORS] = {\n");
        for (int i = 0; i < n; i++) {
            List<NeighborJson> nbs = neighbors(nodes.get(i));
            sb.append("    {");
            for (int j = 0; j < maxN; j++) {
                sb.append(j < nbs.size() ? nbs.get(j).edgeWeight + "f" : "0.0f");
                if (j < maxN - 1) sb.append(", ");
            }
            sb.append("}");
            if (i < n - 1) sb.append(",");
            sb.append("\n");
        }
        sb.append("};\n");

        return sb.toString();
    }

    private static List<NeighborJson> neighbors(NodeJson node) {
        return node.neighbors != null ? node.neighbors : Collections.emptyList();
    }
}
