// Auto-generated by TopologyCompiler — do not edit by hand
#pragma once
#include <stdint.h>
#include <stdbool.h>

#define NUM_NODES 4
#define MAX_NEIGHBORS 2

static const char* const NODE_IDS[NUM_NODES] = {"1A", "1B", "1C", "1Exit-A"};
static const bool IS_EXIT[NUM_NODES] = {false, false, false, true};

static const int8_t NEIGHBOR_IDX[NUM_NODES][MAX_NEIGHBORS] = {
    {1, 2},   // 1A
    {0, 3},   // 1B
    {0, 3},   // 1C
    {1, 2}   // 1Exit-A
};

static const float WEIGHTS[NUM_NODES][MAX_NEIGHBORS] = {
    {5.0f, 3.0f},
    {5.0f, 7.0f},
    {3.0f, 4.0f},
    {7.0f, 4.0f}
};

// NODE_PORT[i]: which Mega hardware serial port talks directly to node i.
// 1 = Serial1 (TX1 pin18 / RX1 pin19)
// 2 = Serial2 (TX2 pin16 / RX2 pin17)
// 0 = no direct UART connection (topology-only node, not a physical ESP32)
static const int8_t NODE_PORT[NUM_NODES] = {1, 2, 0, 0};
// 1A -> Serial1, 1B -> Serial2, 1C -> not wired, 1Exit-A -> not wired
